--USE DataWarehouseAnalytics
-- Explore all objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all Cloumns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'gold.dim_customers'

-- Explore Dimensions
SELECT DISTINCT
country
FROM [gold.dim_customers]

-- Explore all categories "The major divisions"
SELECT DISTINCT category,sub_category, product_name FROM [gold.dim_products]

-- Exploring Date columns
SELECT 
MIN(order_date) AS first_order_date, 
MAX(order_date) AS last_order_date, 
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS years_in_service 
FROM [gold.fact_sales]

-- Find Total Sales
SELECT SUM(sales_amount) AS total_sales FROM [gold.fact_sales]

-- Find how many items sold
SELECT SUM(quantity) AS total_items_sold FROM [gold.fact_sales]

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM [gold.fact_sales]

-- Find total number of orders
SELECT COUNT(order_number) AS total_order_count FROM [gold.fact_sales]
SELECT COUNT(DISTINCT order_number) AS total_order_count FROM [gold.fact_sales]

-- Find total number of products
SELECT COUNT(DISTINCT product_key) AS total_products FROM [gold.fact_sales]

-- Find total number of customers
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM [gold.fact_sales]

-- Find total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM [gold.fact_sales]

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) FROM [gold.fact_sales]
UNION ALL
SELECT 'Average Price' as measure_name, AVG(price) FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Orders' as measure_name, COUNT(DISTINCT order_number) FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Products' as measure_name, COUNT(DISTINCT product_key) FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Customers' as measure_name, COUNT(DISTINCT customer_key) FROM [gold.fact_sales]
UNION ALL
SELECT 'Total Customers who placed order' as measure_name, COUNT(DISTINCT customer_key) FROM [gold.fact_sales]

-- ===========Measures by Dimensions==========

-- Find total customers by countries
SELECT DISTINCT country,
COUNT(DISTINCT customer_key) AS total_customer
FROM [gold.dim_customers]
GROUP BY country
ORDER BY total_customer DESC

-- Find total customers by gender
SELECT DISTINCT gender,
COUNT(DISTINCT customer_key) AS total_customer
FROM [gold.dim_customers]
GROUP BY gender
ORDER BY total_customer DESC

-- Find total products by category
SELECT DISTINCT category,
COUNT(DISTINCT product_key) AS total_products
FROM [gold.dim_products]
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT DISTINCT pr.sub_category,
AVG(sa.price) AS average_cost
FROM [gold.fact_sales]sa
LEFT JOIN 
[gold.dim_products]pr
ON pr.product_key = sa.product_key
GROUP BY pr.sub_category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT DISTINCT pr.category,
SUM(sa.sales_amount) AS total_revenue
FROM [gold.fact_sales]sa
LEFT JOIN 
[gold.dim_products]pr
ON pr.product_key = sa.product_key
GROUP BY pr.category
ORDER BY total_revenue DESC

-- Find total revenue generated by each customer.
SELECT cu.first_name,
SUM(sa.sales_amount) AS total_revenue
FROM [gold.fact_sales]sa
LEFT JOIN [gold.dim_customers]cu
ON cu.customer_key = sa.customer_key
GROUP BY cu.first_name
ORDER BY total_revenue DESC


-- What is the distribution of sold items across countries?
SELECT DISTINCT cu.country,
SUM(sa.quantity) AS sold_items
FROM [gold.dim_customers]cu
LEFT JOIN
[gold.fact_sales]sa
ON sa.customer_key = cu.customer_key
GROUP BY cu.country
ORDER BY sold_items DESC

-- ===============Ranking analysis==============
-- Which 5 products generate the highest revenue?
SELECT TOP 5
pr.product_name,
SUM(sa.sales_amount) AS total_revenue
FROM [gold.fact_sales]sa
LEFT JOIN 
[gold.dim_products]pr
ON pr.product_key = sa.product_key
GROUP BY pr.product_name
ORDER BY total_revenue DESC

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
pr.product_name,
SUM(sa.sales_amount) AS total_revenue
FROM [gold.fact_sales]sa
LEFT JOIN 
[gold.dim_products]pr
ON pr.product_key = sa.product_key
GROUP BY pr.product_name
ORDER BY total_revenue

-- Window functions to solve complex questions
SELECT *
FROM(
	SELECT
	pr.product_name,
	SUM(sa.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(sa.sales_amount) DESC) AS rank_products
	FROM [gold.fact_sales]sa 
	LEFT JOIN 
	[gold.dim_products]pr
	ON pr.product_key = sa.product_key
	GROUP BY pr.product_name)t
WHERE rank_products <= 5
